apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gel.fullname" . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      {{- include "gel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gel.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.gel.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GEL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "resource.default.name"  . }}-server-password
            {{- if .Values.gel.security.tls.enabled }}
            - name: GEL_SERVER_TLS_CERT_FILE
              value: /etc/gel/tls/tls.crt
            - name: GEL_SERVER_TLS_KEY_FILE
              value: /etc/gel/tls/tls.key
            {{- else }}
            - name: EDGEDB_SERVER_SECURITY
              value: insecure_dev_mode
            - name: EDGEDB_SERVER_TLS_CERT_MODE
              value: generate_self_signed
            {{- end }}
            - name: EDGEDB_SERVER_RUNSTATE_DIR
              value: /tmp/gel
            - name: EDGEDB_SERVER_INSTANCE_NAME
              value: "{{ .Release.Name }}"
            - name: EDGEDB_SERVER_ADMIN_UI
              value: enabled
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gel.backend.secretName }}
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gel.backend.secretName }}
                  key: password
            - name: PG_SVC
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gel.backend.secretName }}
                  key: host
            - name: GEL_PORT  # Only to fix https://github.com/edgedb/edgedb-docker/issues/69
              value: {{ .Values.gel.container.port | quote}}
            - name: GEL_SERVER_BACKEND_DSN
              value: "postgresql://$(PG_USER):$(PG_PASSWORD)@$(PG_SVC)?sslmode=disable"
          ports:
            - containerPort: {{ .Values.gel.container.port }}
              name: {{ .Values.gel.container.portName }}
          startupProbe:
            httpGet:
              path: /server/status/alive
              port: {{ .Values.gel.container.port }}
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /server/status/alive
              port: {{ .Values.gel.container.port }}
          readinessProbe:
            httpGet:
              path: /server/status/ready
              port: {{ .Values.gel.container.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.gel.security.tls.enabled }}
          volumeMounts:
            - name: {{ .Values.gel.security.tls.secretName }}
              mountPath: /etc/gel/tls
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.gel.security.tls.enabled }}
      volumes:
        - name: gel-tls
          secret:
            secretName: {{ .Values.gel.security.tls.secretName }}
      {{- end }}
