checks:
  addAllBuiltIn: true
  exclude:
    - "no-read-only-root-fs"
    - "required-annotation-email"
    - "required-label-owner"
    - "read-secret-from-env-var"
    - "use-namespace"
    - "dnsconfig-options"
    - "no-node-affinity"
    - "minimum-three-replicas"
    - "dangling-networkpolicy"
    - "sorted-keys"  # Sorting YAML keys alphabetically is not a priority.
    - "env-value-from"  # Secret is created dynamically by CloudNativePG Cluster CRD.
