apiVersion: v2
appVersion: "7.0"
type: application
name: gel
description: A Helm chart for deploying the Gel graph database.
home: https://github.com/giantswarm/gel-app
icon: https://s.giantswarm.io/app-icons/edgedb/light.svg
sources:
  - https://github.com/edgedb/edgedb
  - https://github.com/Japan7/nanak8s/tree/main/charts/edgedb
version: 1.0.1
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
