name: gel
serviceType: managed

replicaCount: 1

image:
  registry: gsoci.azurecr.io
  name: giantswarm/gel
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

gel:
  args:
    - "--enable-backend-adaptive-ha"
  backend:
    secretName: gel-postgres-superuser
  container:
    port: &containerPort 5656
    portName: &containerPortName gel
  security:
    tls:
      enabled: true
      issuerName: selfsigned-giantswarm
      secretName: gel-tls
    serverPassword:
      secretName: gel-server-password

postgres:
  cnpg:
    enabled: true
    instances: 2
    storage:
      size: 1Gi
    monitoring:
      podMonitor:
        enabled: true
        labels: {}
    imageCatalogRef:
      major: 16
      name: gs-postgresql
    switchoverDelay: 60

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

monitoring:
  serviceMonitor:
    enabled: true

podAnnotations: {}

podSecurityContext:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: *containerPort
  portName: *containerPortName

networkPolicy:
  enabled: true

ciliumNetworkPolicy:
  enabled: true

resources:
  limits:
    cpu: 250m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 1024Mi

# Use either HPA or VPA, but not both.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Use either HPA or VPA, but not both.
vpa:
  enabled: true
  containerPolicies:
    minAllowed:
      cpu: "250m"
      memory: "1024Mi"  # gel has a 1GB minimum.

nodeSelector: {}

tolerations: []

affinity: {}
