{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "gel.fullname" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
       {{- include "gel.selectorLabels" . | nindent 6 }}
  egress:
    # Allow egress to database pods.
    # This assumes the Postgres cluster is the CNPG cluster included in this app. A separate policy is needed if using other Postgres clusters.
    - toEndpoints:
        - matchLabels:        
            cnpg.io/cluster: {{ include "gel.pgClusterName" . }}
      toPorts:
      - ports:
        - port: "5432"
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "5656"
      - port: "9187"
{{ if .Values.postgres.cnpg.enabled -}}
---
# This policy targets PostgreSQL database pods managed outside this app, but deployed from this app's CNPG Cluster resource.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "gel.fullname" . }}-pg-cluster
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "gel.pgClusterName" . }}
      cnpg.io/podRole: instance
  ingress:
    - fromEndpoints:
        # Allow ingress to the Gel PostgreSQL cluster from a Gel application pod in the same namespace.
        - matchLabels:
            {{- include "gel.selectorLabels" . | nindent 12 }}
        # Allow ingress from other CNPG cluster members (including join pods).
        - matchLabels:
            cnpg.io/cluster: {{ include "gel.pgClusterName" . }}
      toPorts:
        - ports:
            - port: "5432"
  egress:
    # Allow egress to other CNPG cluster members.
    - toEndpoints:
        - matchLabels:        
            cnpg.io/cluster: {{ include "gel.pgClusterName" . }}
      toPorts:
        - ports:
            - port: "5432"
{{ end }}
{{ end }}
