{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gel.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 5656
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
