{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gel.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 5656
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{ if .Values.postgres.cnpg.enabled -}}
---
# This policy targets PostgreSQL database pods managed outside this app, but deployed from this app's CNPG Cluster resource.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "gel.pgClusterName" . }}
      cnpg.io/podRole: instance
  ingress:
  - ports:
    - port: 5432
      protocol: TCP
    - port: 8000
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
{{- end }}
