{{- if .Values.postgres.cnpg.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "gel.pgClusterName" . }}
  namespace: {{ include "resource.default.namespace"  . }}
spec:
  instances: {{ .Values.postgres.cnpg.instances }}

  storage:
    size: {{ .Values.postgres.cnpg.storage.size }}

  monitoring:
    enablePodMonitor: {{ .Values.postgres.cnpg.monitoring.podMonitor.enabled }}
    podMonitorAdditionalLabels:
    {{- with .Values.postgres.cnpg.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 6 }}
    {{- end}}

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: {{ .Values.postgres.cnpg.imageCatalogRef.major }}
    name: {{ .Values.postgres.cnpg.imageCatalogRef.name }}
  
  # Shutdown behavior is optimized for fast recovery time, at the expense of potential data loss.
  smartShutdownTimeout: 30
  stopDelay: 60
  switchoverDelay: {{ .Values.postgres.cnpg.switchoverDelay }}
  
  enableSuperuserAccess: true
{{- end -}}
