apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name"  . }}-server-password
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "gel.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}

