{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "gel.labels" . | nindent 4 }}
  {{- with .Values.monitoring.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: {{ .Values.gel.container.portName | quote }}
      {{- if .Values.monitoring.serviceMonitor.interval}}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.scrapeTimeout}}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- end }}      
      {{- with .Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: ca.crt
            name: {{ .Values.gel.security.tls.secretName }}
        cert:
          secret:
            key: tls.crt
            name: {{ .Values.gel.security.tls.secretName }}
        keySecret:
          key: tls.key
          name: {{ .Values.gel.security.tls.secretName }}
        serverName: {{ include "gel.fullname" . }}
  selector:
    matchLabels:
  {{- include "gel.selectorLabels" . | nindent 6 }}
{{- end }}
