apiVersion: v1
kind: Service
metadata:
  name: {{ include "gel.fullname" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.portName | quote }}
  selector:
    {{- include "gel.selectorLabels" . | nindent 4 }}
